### ISSUE TITLE
currencySymbol should change on the fly

### ISSUE THREAD

**Issue by tom94zoe** [aguirrel/ng-currency#81] opened 2016-06-16 13:53 UTC
Hi, 

Because the currencySymbol is one-way binded (@) it doesn't realize if the symbol has been changed. 
Is there a workaround for this problem? I need this featured because my symbol gets loaded dynamically.

thank you

**Comment by tom94zoe** [comment] 2016-06-17 12:22
Today I have seen that the scope paramteres get handled with attributes.observe(). However, the issue is still there.

**Comment by tom94zoe** [comment] 2016-06-22 14:25
I changed 
 ```
  attrs.$observe('currencySymbol', function(v) {
                  scope.currencySymbol = v;
})
```

to 

  ```
 attrs.$observe('currencySymbol', function(v) {
                  scope.currencySymbol = v;
                  reformatViewValue()
                });
```

now it works, but that is not the best solution, is it?

**Comment by jjoekoullas** [comment] 2016-07-11 19:27
This looks like it may be a duplicate of #77

**Comment by tom94zoe** [comment] 2016-07-15 09:11
That's true. 
At first I thought that a broadcast isn't nice because we use the "controller as" syntax. 
But after reading an article of Todd Motto, I recognised that a broadcast is the only possible solution. 

Now I have the problem that the broadcast gets fired before the currency was set. Does anyone have a solution for this problem? Now a timeout is the workaround for this problem, as you can see in the following code part. 

ctrl.changedCurrency = function (changed) {
        ctrl.symbol = ctrl.currencyIso === 'EUR' ? '€' : '';
};

      $scope.$watch(function () {
        return ctrl.symbol;
      }, function (newVal, oldVal) {
        setTimeout(function () {
          $scope.$broadcast("currencyRedraw");
        }, 300);
})


<input ng-model="$ctrl.order.amount" ng-currency currency-symbol="{{$ctrl.symbol}}"/>
    
<md-select flex ng-model="$ctrl.currencyIso"  ng-change="$ctrl.changedCurrency()">
            <md-option ng-repeat="currency in $ctrl.possibleCurrency" ng-value="currency.key">
              {{currency.description}}
            </md-option>
</md-select>


I also tried invoking the broadcast at the end of changeCurrency, but that wasn't the solution.

**Comment by aguirrel** [comment] 2016-07-15 10:50
It's odd that invoking the broadcast at the end of changeCurrency doesn't work.

Why do you use: ctrl.currencyIso === 'EUR' ? '€' : ''; ? in this case only € will work.

Could you try?

```
ctrl.changedCurrency = function (changed) {
    ctrl.symbol = ctrl.currencyIso;
    $scope.$broadcast("currencyRedraw");
  };
```

**Comment by tom94zoe** [comment] 2016-07-15 11:00
I use ctrl.currencyIso === 'EUR' ? '€' : ''; ?  as stub, because the array of symbols isn't ready yet. 

I tried this already. The shown symbol is the ISO of the currency which was choosen before.

**Comment by aguirrel** [comment] 2016-07-15 11:13
ok, but have you tried exactly this code? Sorry for asking but I have to reproduce it and I need the minimum code ;)

```
ctrl.changedCurrency = function (changed) {
    ctrl.symbol = ctrl.currencyIso;
    $scope.$broadcast("currencyRedraw");
  };
```

**Comment by tom94zoe** [comment] 2016-07-15 11:23
Yes exactly

**Comment by aguirrel** [comment] 2016-07-15 11:34
Really sorry, but I don't get it, if the following code works for you: "the shown symbol is the ISO of the currency which was choosen before".  Why shoud be the $observe changed.  

```
ctrl.changedCurrency = function (changed) {
    ctrl.symbol = ctrl.currencyIso;
    $scope.$broadcast("currencyRedraw");
  };
```

**Comment by tom94zoe** [comment] 2016-07-15 11:56
It could be I have not expressed myself clearly. 

The shown symbol isn't the current currencyIso, but it is the currencyIso which I have selected before the current one/the previous on. So the code above doesn't work for me as it should be.

sample: 
1. current selected currency: nothing, current shown symbol: nothing
2. current selected currency: Dollar, current shown symbol: nothing
3. current selected currency: Euro, current shown symbol: USD
4. current selected currency: Pound, current shown symbol: EUR

**Comment by aguirrel** [comment] 2016-07-15 12:00
ah! ok! I understand now. Let me check it.

**Comment by aguirrel** [comment] 2016-07-27 17:29
Hi @tom94zoe, please, try src/ng-currency-js in master branch to check if it works fine to you.

Thanks a lot!

**Comment by tom94zoe** [comment] 2016-07-28 06:30
Thank you, src/ng-currency-js works for me.

**Comment by aguirrel** [comment] 2016-07-29 12:45
Great! I'm closing this issue, it will be available in the next release. Thanks!

**Closed by aguirrel** 2016-07-29 12:45 UTC
