### ISSUE TITLE
Does not work with dynamic fields

### ISSUE THREAD

**Issue by holtc** [aguirrel/ng-currency#44] opened 2015-10-01 14:34 UTC
I have two questions.

1) Is there any way to update on debounce, rather than blur?

2) I am trying to do something in an ng-repeat ("question in questions") and ng-currency is creating parsing issues.  Is it possible to use ng-currency in this way?  It is working fine without ng-currency, but I would love to use the currency formatting.

```
<input ng-currency type="text" class="form-control" 
			    	name="{{question.name}}" placeholder="{{question.placeholder}}"
			    	 ng-model-options="{ debounce: 200 }" ng-required="{{question.required}}"
			    	 min="{{question.min}}" max="{{question.max}}"
			    	 ng-model="model[question.name]">
```
And here is the copied and pasted error text: 
Syntax Error: Token '{' invalid key at column 2 of the expression [{{question.min}}] starting at [{question.min}}].

If I remove the min field, then the parse issue shifts to the max or required fields, etc.

Thanks!

**Comment by aguirrel** [comment] 2015-10-01 18:05
Hi @holtc thanks for reporting this issue.  I'm cheking it.

**Comment by aguirrel** [comment] 2015-10-01 18:07
Did you try just using min="question.min" instead of min="{{question.min}}"?

**Comment by holtc** [comment] 2015-10-01 18:18
Yeah, but then the min field is the literal "question.min" rather than "0", which is the value stored in the question.min variable

**Comment by aguirrel** [comment] 2015-10-01 18:22
In this case as is an angular directive works as ng-model that you don't use {{}} for get the value.  I did a try and worked like a charm.  Please, tell me if it doesn't work for you. ;)

**Comment by aguirrel** [comment] 2015-10-01 18:23
Thank you! Please feel free to reopen this ticket if you have issues.

**Comment by holtc** [comment] 2015-10-01 18:33
Is there a way to conditionally add the fraction field?  the directive itself has ng-currency={{boolean}}, but is there something similar for the fraction field?  Thanks!

**Comment by aguirrel** [comment] 2015-10-01 18:38
if you don't need fractions just set it with zero "0", it disables fractions.

**Comment by holtc** [comment] 2015-10-01 18:40
I have ng-currency=false, but the fractions="0" field is still there, since the ng-currency={{boolean}} is set dynamically.  However, this breaks, because it says the input is not a number, which I assume is caused by the fraction="0" field still being there although ng-currency=false

**Comment by holtc** [comment] 2015-10-01 18:43
Nevermind, actually, this has been resolved.  Thanks! This directive is awesome

**Comment by holtc** [comment] 2015-10-01 19:25
Is there is a way to update on change/on debounce, rather than on blur?

**Comment by holtc** [comment] 2015-10-01 20:12
Also, I can confirm the min and max validations do not work when ng-currency=false

**Comment by holtc** [comment] 2015-10-02 00:54
Have made a workaround, I just make everything a currency, and for those values that are not actually a currency, but just a number, I pass currency-symbol="" and fraction="0"

**Comment by aguirrel** [comment] 2015-10-02 11:26
Hi @holtc!

Just for the record:

* Is there is a way to update on change/on debounce, rather than on blur?
When I started this directive my first impression was "on change" should be the trigger which format data to currency, but then I realize that onblur is much simple and at least equal efective.  Anyway I will give onchange a try on next releases ;)

* Also, I can confirm the min and max validations do not work when ng-currency=false
Yes, because min and max are for type=number, ng-currency only works on type=text.  Explanation is here #37 

Thanks a lot!

**Comment by holtc** [comment] 2015-10-02 13:01
If ng-currency=true though, the min/max validations do work.  Is there some sort of conversion to type=number in the background? 

Thanks!

**Comment by aguirrel** [comment] 2015-10-02 13:42
If ng-currency is true, min and max validator are set (ngModel.$validators.min and ngModel.$validators.max).  But if is false, in the code you have:

<pre>
if (attrs.ngCurrency === 'false') return;
</pre>

before validators are set.  

min and max attributes were created to emulate type=number, but nothing else.

Set ng-currency to false do component not load, even if you set it to true latter.  The same if is set to true and then to false.

**Comment by holtc** [comment] 2015-10-06 16:53
I have made it update on change by adding a few things.  I have added 
`
model: '=ng-model'
`
to the scope object of the directive,

I added a function

`
function update() {
    scope.$watch("model", function() {
        ngModel.$commitViewValue();
        reformatViewValue(); 
    });
}
`
which watches the model for changes, and I call the update() function in 2 existing methods,

`
ngModel.$validators.min = function(cVal) {
    if (!scope.ngRequired && isNaN(cVal)) {
        return true;
    }
    if(typeof scope.min  !== 'undefined') {
        return cVal >= parseFloat(scope.min);
    }
    update();
    return true;
};

ngModel.$validators.max = function(cVal) {
    if (!scope.ngRequired && isNaN(cVal)) {
        return true;
    }
    if(typeof scope.max  !== 'undefined') {
        return cVal <= parseFloat(scope.max);
    }
    update();
    return true;
};
`

I am not sure if this is the best/correct place to call the update() method, but it has the desired effect.  Let me know what you think!

**Comment by aguirrel** [comment] 2015-10-06 17:04
Hi @holtc!

When you call update for the first time, it binds changed in model with the function defined.  Why you call it every time you check for min and max?  What is exactly what you need to do?  

Please, check ng-currency code, I added this weekend some code and you cloud take $watch for min and max variable to get an idea how does it work ;)

**Comment by holtc** [comment] 2015-10-06 17:34
If there is a validation error, update does not work, and also in some cases, the update function does not pick up the changes to the model if I delete 1 digit from the number.  However, putting it in the validation functions has completely fixed this problem.

**Comment by aguirrel** [comment] 2015-10-08 14:49
Ok, please let me get this straight :)  You need to update input view on change, is it right?

Did you try listening for keydown or keypress event?

<pre>
element.on("keydown", function () { ... } );
</pre>

**Comment by holtc** [comment] 2015-10-08 15:55
Yes, I wanted to update on change.  I hadn't tried that because it worked when I had added it into those functions.

**Comment by aguirrel** [comment] 2015-10-08 18:18
ok, may you give a try using on keydown?  It's very interesting and clear way to add this feature to directive.

Checking your code I see it could be refactores as:

From:
<pre>
function update() {
    scope.$watch("model", function() {
        ngModel.$commitViewValue();
        reformatViewValue(); 
    });
}
</pre>

to 

<pre>
scope.$watch("model", function() {
  update()    
});

function update() {
    ngModel.$commitViewValue();
    reformatViewValue(); 
}
</pre>

So you don't $watch variable many times becouse I don't know if it could have a side efect.

**Comment by aguirrel** [comment] 2015-12-02 11:54
Hi  @holtc, I have added a listener which redraw all ng-currency fields.  Perhaps this is a more clear way to fix your issue.

You can use $scope.$broadcast("currencyRedraw");

It's in master branch right now and I will be in next release. ;)

Best regards,

Luis

**Closed by aguirrel** 2015-12-02 11:54 UTC

**Comment by aguirrel** [comment] 2015-12-02 12:31
Please, update to version 0.8.12 to try currencyRedraw event.

Thanks!

Luis
